package com.example.login.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.login.bean.TabData;

import com.example.login.db.TabDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tabDataDaoConfig;

    private final TabDataDao tabDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tabDataDaoConfig = daoConfigMap.get(TabDataDao.class).clone();
        tabDataDaoConfig.initIdentityScope(type);

        tabDataDao = new TabDataDao(tabDataDaoConfig, this);

        registerDao(TabData.class, tabDataDao);
    }
    
    public void clear() {
        tabDataDaoConfig.clearIdentityScope();
    }

    public TabDataDao getTabDataDao() {
        return tabDataDao;
    }

}
